<?php

function my_module_menu() {
        $items = array();
	$items['my_module/form'] = array(
	   'title' => t('My form'),
	   'page callback' => 'my_module_form',
	   'acess arguments' => array('access content'),
	   'description' => t('My form'),
	   'type' => MENU_CALLBACK,
	   );
	   return $items;
   }
   
   function my_module_form() {
	   return drupal_get_form('my_module_my_form');
   }
   
   function my_module_my_form($form_state) {
	 $form['name'] = array(
          '#type' => 'fieldset',
          '#title' => t('Name'),
          '#collapsible' => TRUE,
          '#collapsed' => FALSE,
         );
         $form['name']['user'] = array(
          '#type' => 'textfield',
          '#title' => t('username'),
          '#required' => TRUE,
          '#default_value' => "username",
          '#description' => "enter your username.",
          '#size' => 20,
          '#maxlength' => 20,
         );
         $form['file'] = array(
          '#type' => 'file',
          '#title' => t('Image'),
          '#description' => t('Upload a file, allowed extensions: jpg, jpeg, png, gif'),
         );
         $form['submit'] = array(
          '#type' => 'submit',
          '#value' => 'Submit',
         );
         return $form;
	 }
	 
   function my_module_my_form_submit($form, &$form_state) {
        drupal_set_message(t('The form has been submitted.'));
     }

	
